const CLIENTS = [
  {
    id: 1, tramite: "Noi", cliente: "Milan Kelemen",
    data: "09/03", regist: "DOC", carta: "X", deposito: 980, tel: 3,
    flipping: "—", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 961, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 961, bloc: false, log: "",
    tramiti: 25, clienti: 0,
    username: "X", password: "X", parolaSegreta: ""
  },
  {
    id: 2, tramite: "Yuri", cliente: "Francesco Monti",
    data: "19/03", regist: "SPID", carta: "X", deposito: 980, tel: 4,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 880, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 880, bloc: false, log: "",
    tramiti: 15, clienti: 25,
    username: "franceacop", password: "SnaiFra1896@", parolaSegreta: ""
  },
  {
    id: 3, tramite: "Amedeo Morelato", cliente: "Fadwa",
    data: "19/03", regist: "SPID", carta: "X", deposito: 980, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 888, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 888, bloc: false, log: "Ho prelevato Giulia Arena, 300€ subito",
    tramiti: 15, clienti: 25,
    username: "fadwaelmourtadi", password: "@Lacimolala020", parolaSegreta: ""
  },
  {
    id: 4, tramite: "Yuri", cliente: "Yassine Sadkani",
    data: "23/03", regist: "DOC", carta: "X", deposito: 980, tel: 4,
    flipping: "HALLOWEEN FORTUNE", wagering: "HIGHWAY KINGS",
    fermato: 7795, arrivato: 3750,
    esito: "VINTO", statoFunBonus: "SBLOCCATO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 867, info1: "", prel2: 910, info2: "", prel3: 951, info3: "",
    rititatiTot: 2728, bloc: false, log: "",
    tramiti: 30, clienti: 50,
    username: "Memedesimoo", password: "Goldengroup1!", parolaSegreta: "star wars"
  },
  {
    id: 5, tramite: "Emma Poli", cliente: "Angelica Larini",
    data: "24/03", regist: "DOC", carta: "X", deposito: 980, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 959, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 959, bloc: false, log: "",
    tramiti: 15, clienti: 25,
    username: "larini_angelica", password: "Lapizza08!", parolaSegreta: "Giuseppe"
  },
  {
    id: 6, tramite: "Chiara Meggetto", cliente: "Dalila Driouche",
    data: "30/03", regist: "DOC", carta: "X", deposito: 980, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 952, prelevati: "SÌ",
    prel1: 952, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 952, bloc: false, log: "",
    tramiti: 15, clienti: 25,
    username: "ddaalilaa", password: "DDriouchE55*", parolaSegreta: "cime tempestose"
  },
  {
    id: 7, tramite: "Stefano Manzini", cliente: "Giorgio Perrina",
    data: "01/04", regist: "DOC", carta: "X", deposito: 997, tel: 4,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 990, prelevati: "SÌ",
    prel1: 974, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 974, bloc: false, log: "",
    tramiti: 15, clienti: 25,
    username: "G1orgio21", password: "Kebabbo12$", parolaSegreta: "harry potter"
  },
  {
    id: 8, tramite: "Chiara Meggetto", cliente: "Diego Pagano",
    data: "16/03", regist: "SPID", carta: "X", deposito: 980, tel: 4,
    flipping: "HALLOWEEN FORTUNE", wagering: "HALLOWEEN FORTUNE",
    fermato: 4700, arrivato: 840,
    esito: "VINTO", statoFunBonus: "SBLOCCATO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 1800, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 1800, bloc: true, log: "",
    tramiti: 30, clienti: 50,
    username: "diegopagano", password: "Thespecial2007!", parolaSegreta: ""
  },
  {
    id: 9, tramite: "Roberto Lungu", cliente: "Gaia Fusco",
    data: "01/04", regist: "DOC", carta: "X", deposito: 997, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 980, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 980, bloc: true, log: "",
    tramiti: 15, clienti: 25,
    username: "gaia1701", password: "Jkyuws4920.", parolaSegreta: ""
  },
  {
    id: 10, tramite: "Noi", cliente: "Fabio Viana",
    data: "04/04", regist: "SPID", carta: "X", deposito: 980, tel: 2,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 4, prelevati: "SÌ",
    prel1: 300, info1: "09/04", prel2: 662, info2: "10/04", prel3: 0, info3: "",
    rititatiTot: 962, bloc: false, log: "",
    tramiti: 25, clienti: 0,
    username: "fabioo_mog", password: "Fafviana.2007", parolaSegreta: "Inter"
  },
  {
    id: 11, tramite: "Noi", cliente: "Giulia Arena",
    data: "01/04", regist: "DOC", carta: "X", deposito: 980, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 300, info1: "09/04", prel2: 655, info2: "12/04", prel3: 0, info3: "",
    rititatiTot: 955, bloc: false, log: "",
    tramiti: 25, clienti: 0,
    username: "Giuly.are7", password: "Giuly1204!", parolaSegreta: ""
  },
  {
    id: 12, tramite: "Sofia Nanni", cliente: "Lucrezia Capocchi",
    data: "07/04", regist: "DOC", carta: "X", deposito: 980, tel: 3,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 315, info1: "10/04", prel2: 657, info2: "12/04", prel3: 0, info3: "",
    rititatiTot: 972, bloc: false, log: "",
    tramiti: 15, clienti: 25,
    username: "Lucreziacapo08", password: "Giocomania08!", parolaSegreta: "Juve"
  },
  {
    id: 13, tramite: "Sofia Nanni", cliente: "Matilde Cerri",
    data: "11/04", regist: "DOC", carta: "REV", deposito: 980, tel: 4,
    flipping: "—", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 0, prelevati: "SÌ",
    prel1: 0, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 0, bloc: false, log: "",
    tramiti: 0, clienti: 0,
    username: "maticerri", password: "webmug-gusdEs-necby4", parolaSegreta: ""
  },
  {
    id: 14, tramite: "Andrea Dimajo", cliente: "Roberto Lungu",
    data: "28/03", regist: "DOC", carta: "X", deposito: 980, tel: 2,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 951, prelevati: "DA RIFARE",
    prel1: 951, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 951, bloc: true, log: "DA SBLOCCARE",
    tramiti: 15, clienti: 25,
    username: "Roberto2006Lungu", password: "Roberto2006!", parolaSegreta: "Bayern München"
  },
  {
    id: 15, tramite: "Noi", cliente: "Tommaso Valbusa",
    data: "12/04", regist: "DOC", carta: "REV", deposito: 980, tel: 2,
    flipping: "HALLOWEEN FORTUNE", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "PERSO", statoFunBonus: "PERSO", statoSaldo: "SBLOCCATO",
    daPrel: 603, prelevati: "IN CORSO",
    prel1: 360, info1: "13/04", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 360, bloc: false, log: "Prelevati prima parte",
    tramiti: 15, clienti: 25,
    username: "TommasoValbusa", password: "Tommy!1001", parolaSegreta: "davide"
  },
  {
    id: 16, tramite: "Noi", cliente: "Rossana Forma",
    data: "12/04", regist: "DOC", carta: "", deposito: 0, tel: 0,
    flipping: "—", wagering: "—",
    fermato: 0, arrivato: 0,
    esito: "", statoFunBonus: "", statoSaldo: "",
    daPrel: 0, prelevati: "",
    prel1: 0, info1: "", prel2: 0, info2: "", prel3: 0, info3: "",
    rititatiTot: 0, bloc: false, log: "",
    tramiti: 0, clienti: 0,
    username: "Ross.ana_", password: "Snai.26!", parolaSegreta: ""
  }
];
